# telegram
windowrule = workspace special:tg, class:^(org.telegram.desktop)
bind = $mainMod, t, togglespecialworkspace, tg
workspace =  special:tg, on-created-empty:Telegram -- %u

# browser
workspace = name:web, on-created-empty:firefox
windowrule = workspace name:web, tag:browser*
bind = $mainMod SHIFT, B, exec, $browser
bind = $mainMod, B, workspace, name:web

windowrule = workspace name:tor, class:^(Tor Browser)$

#special
bind = $mainMod, o, workspace, special:overlay
workspace =  special:overlay, on-created-empty:kitty







