# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #DEE2EA
background         #2B2120
cursor             #838790

active_tab_foreground     #2B2120
active_tab_background     #DEE2EA
inactive_tab_foreground   #DEE2EA
inactive_tab_background   #2B2120

active_border_color   #DEE2EA
inactive_border_color #2B2120
bell_border_color     #330D0F

color0      #524645
color1		#330D0F
color2		#1E2228
color3		#3A404B
color4		#3C424E
color5		#4A525E
color6		#788192
color7		#C7CDD9
color8		#8B9098
color9		#441114
color10		#282D36
color11		#4E5664
color12		#505867
color13		#636D7E
color14		#A0ACC3
color15		#C7CDD9
