# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(2B2120)
$foreground = rgb(DEE2EA)
$color0 = rgb(524645)
$color1 = rgb(330D0F)
$color2 = rgb(1E2228)
$color3 = rgb(3A404B)
$color4 = rgb(3C424E)
$color5 = rgb(4A525E)
$color6 = rgb(788192)
$color7 = rgb(C7CDD9)
$color8 = rgb(8B9098)
$color9 = rgb(441114)
$color10 = rgb(282D36)
$color11 = rgb(4E5664)
$color12 = rgb(505867)
$color13 = rgb(636D7E)
$color14 = rgb(A0ACC3)
$color15 = rgb(C7CDD9)
